//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Acig_Help_DeskModel", "FK_Sub_Categories_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Acig_Help_DeskModel.Category), "Sub_Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acig_Help_DeskModel.Sub_Categories), true)]
[assembly: EdmRelationshipAttribute("Acig_Help_DeskModel", "FK_Events_Tickets", "Ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Acig_Help_DeskModel.Ticket), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acig_Help_DeskModel.Event), true)]
[assembly: EdmRelationshipAttribute("Acig_Help_DeskModel", "FK_Tickets_Sub_Categories", "Sub_Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Acig_Help_DeskModel.Sub_Categories), "Ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Acig_Help_DeskModel.Ticket), true)]

#endregion

namespace Acig_Help_DeskModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Acig_Help_DeskEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Acig_Help_DeskEntities object using the connection string found in the 'Acig_Help_DeskEntities' section of the application configuration file.
        /// </summary>
        public Acig_Help_DeskEntities() : base("name=Acig_Help_DeskEntities", "Acig_Help_DeskEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Acig_Help_DeskEntities object.
        /// </summary>
        public Acig_Help_DeskEntities(string connectionString) : base(connectionString, "Acig_Help_DeskEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Acig_Help_DeskEntities object.
        /// </summary>
        public Acig_Help_DeskEntities(EntityConnection connection) : base(connection, "Acig_Help_DeskEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sub_Categories> Sub_Categories
        {
            get
            {
                if ((_Sub_Categories == null))
                {
                    _Sub_Categories = base.CreateObjectSet<Sub_Categories>("Sub_Categories");
                }
                return _Sub_Categories;
            }
        }
        private ObjectSet<Sub_Categories> _Sub_Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ticket> Tickets
        {
            get
            {
                if ((_Tickets == null))
                {
                    _Tickets = base.CreateObjectSet<Ticket>("Tickets");
                }
                return _Tickets;
            }
        }
        private ObjectSet<Ticket> _Tickets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sub_Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSub_Categories(Sub_Categories sub_Categories)
        {
            base.AddObject("Sub_Categories", sub_Categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tickets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTickets(Ticket ticket)
        {
            base.AddObject("Tickets", ticket);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Acig_Help_DeskModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="created_At">Initial value of the Created_At property.</param>
        /// <param name="updated_At">Initial value of the Updated_At property.</param>
        public static Category CreateCategory(global::System.Int64 id, global::System.String name, global::System.DateTime created_At, global::System.DateTime updated_At)
        {
            Category category = new Category();
            category.Id = id;
            category.Name = name;
            category.Created_At = created_At;
            category.Updated_At = updated_At;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_At
        {
            get
            {
                return _Created_At;
            }
            set
            {
                OnCreated_AtChanging(value);
                ReportPropertyChanging("Created_At");
                _Created_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_At");
                OnCreated_AtChanged();
            }
        }
        private global::System.DateTime _Created_At;
        partial void OnCreated_AtChanging(global::System.DateTime value);
        partial void OnCreated_AtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Updated_At
        {
            get
            {
                return _Updated_At;
            }
            set
            {
                OnUpdated_AtChanging(value);
                ReportPropertyChanging("Updated_At");
                _Updated_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated_At");
                OnUpdated_AtChanged();
            }
        }
        private global::System.DateTime _Updated_At;
        partial void OnUpdated_AtChanging(global::System.DateTime value);
        partial void OnUpdated_AtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Created_By
        {
            get
            {
                return _Created_By;
            }
            set
            {
                OnCreated_ByChanging(value);
                ReportPropertyChanging("Created_By");
                _Created_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_By");
                OnCreated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Created_By;
        partial void OnCreated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnCreated_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Updated_By
        {
            get
            {
                return _Updated_By;
            }
            set
            {
                OnUpdated_ByChanging(value);
                ReportPropertyChanging("Updated_By");
                _Updated_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated_By");
                OnUpdated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Updated_By;
        partial void OnUpdated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnUpdated_ByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Sub_Categories_Categories", "Sub_Categories")]
        public EntityCollection<Sub_Categories> Sub_Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sub_Categories>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Sub_Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sub_Categories>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Sub_Categories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Acig_Help_DeskModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="ticket_Id">Initial value of the Ticket_Id property.</param>
        /// <param name="created_At">Initial value of the Created_At property.</param>
        public static Event CreateEvent(global::System.Int64 id, global::System.String state, global::System.Int64 ticket_Id, global::System.DateTime created_At)
        {
            Event @event = new Event();
            @event.Id = id;
            @event.State = state;
            @event.Ticket_Id = ticket_Id;
            @event.Created_At = created_At;
            return @event;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File1_Name
        {
            get
            {
                return _File1_Name;
            }
            set
            {
                OnFile1_NameChanging(value);
                ReportPropertyChanging("File1_Name");
                _File1_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File1_Name");
                OnFile1_NameChanged();
            }
        }
        private global::System.String _File1_Name;
        partial void OnFile1_NameChanging(global::System.String value);
        partial void OnFile1_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File1_Path
        {
            get
            {
                return _File1_Path;
            }
            set
            {
                OnFile1_PathChanging(value);
                ReportPropertyChanging("File1_Path");
                _File1_Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File1_Path");
                OnFile1_PathChanged();
            }
        }
        private global::System.String _File1_Path;
        partial void OnFile1_PathChanging(global::System.String value);
        partial void OnFile1_PathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File2_Name
        {
            get
            {
                return _File2_Name;
            }
            set
            {
                OnFile2_NameChanging(value);
                ReportPropertyChanging("File2_Name");
                _File2_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File2_Name");
                OnFile2_NameChanged();
            }
        }
        private global::System.String _File2_Name;
        partial void OnFile2_NameChanging(global::System.String value);
        partial void OnFile2_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File2_Path
        {
            get
            {
                return _File2_Path;
            }
            set
            {
                OnFile2_PathChanging(value);
                ReportPropertyChanging("File2_Path");
                _File2_Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File2_Path");
                OnFile2_PathChanged();
            }
        }
        private global::System.String _File2_Path;
        partial void OnFile2_PathChanging(global::System.String value);
        partial void OnFile2_PathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File3_Name
        {
            get
            {
                return _File3_Name;
            }
            set
            {
                OnFile3_NameChanging(value);
                ReportPropertyChanging("File3_Name");
                _File3_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File3_Name");
                OnFile3_NameChanged();
            }
        }
        private global::System.String _File3_Name;
        partial void OnFile3_NameChanging(global::System.String value);
        partial void OnFile3_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String File3_Path
        {
            get
            {
                return _File3_Path;
            }
            set
            {
                OnFile3_PathChanging(value);
                ReportPropertyChanging("File3_Path");
                _File3_Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File3_Path");
                OnFile3_PathChanged();
            }
        }
        private global::System.String _File3_Path;
        partial void OnFile3_PathChanging(global::System.String value);
        partial void OnFile3_PathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Created_By
        {
            get
            {
                return _Created_By;
            }
            set
            {
                OnCreated_ByChanging(value);
                ReportPropertyChanging("Created_By");
                _Created_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_By");
                OnCreated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Created_By;
        partial void OnCreated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnCreated_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Ticket_Id
        {
            get
            {
                return _Ticket_Id;
            }
            set
            {
                OnTicket_IdChanging(value);
                ReportPropertyChanging("Ticket_Id");
                _Ticket_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ticket_Id");
                OnTicket_IdChanged();
            }
        }
        private global::System.Int64 _Ticket_Id;
        partial void OnTicket_IdChanging(global::System.Int64 value);
        partial void OnTicket_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_At
        {
            get
            {
                return _Created_At;
            }
            set
            {
                OnCreated_AtChanging(value);
                ReportPropertyChanging("Created_At");
                _Created_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_At");
                OnCreated_AtChanged();
            }
        }
        private global::System.DateTime _Created_At;
        partial void OnCreated_AtChanging(global::System.DateTime value);
        partial void OnCreated_AtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Events_Tickets", "Ticket")]
        public Ticket Ticket
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("Acig_Help_DeskModel.FK_Events_Tickets", "Ticket").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("Acig_Help_DeskModel.FK_Events_Tickets", "Ticket").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ticket> TicketReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("Acig_Help_DeskModel.FK_Events_Tickets", "Ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ticket>("Acig_Help_DeskModel.FK_Events_Tickets", "Ticket", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Acig_Help_DeskModel", Name="Sub_Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sub_Categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sub_Categories object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="category_Id">Initial value of the Category_Id property.</param>
        /// <param name="created_At">Initial value of the Created_At property.</param>
        /// <param name="updated_At">Initial value of the Updated_At property.</param>
        public static Sub_Categories CreateSub_Categories(global::System.Int64 id, global::System.String name, global::System.Int64 category_Id, global::System.DateTime created_At, global::System.DateTime updated_At)
        {
            Sub_Categories sub_Categories = new Sub_Categories();
            sub_Categories.Id = id;
            sub_Categories.Name = name;
            sub_Categories.Category_Id = category_Id;
            sub_Categories.Created_At = created_At;
            sub_Categories.Updated_At = updated_At;
            return sub_Categories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Category_Id
        {
            get
            {
                return _Category_Id;
            }
            set
            {
                OnCategory_IdChanging(value);
                ReportPropertyChanging("Category_Id");
                _Category_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_Id");
                OnCategory_IdChanged();
            }
        }
        private global::System.Int64 _Category_Id;
        partial void OnCategory_IdChanging(global::System.Int64 value);
        partial void OnCategory_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_At
        {
            get
            {
                return _Created_At;
            }
            set
            {
                OnCreated_AtChanging(value);
                ReportPropertyChanging("Created_At");
                _Created_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_At");
                OnCreated_AtChanged();
            }
        }
        private global::System.DateTime _Created_At;
        partial void OnCreated_AtChanging(global::System.DateTime value);
        partial void OnCreated_AtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Updated_At
        {
            get
            {
                return _Updated_At;
            }
            set
            {
                OnUpdated_AtChanging(value);
                ReportPropertyChanging("Updated_At");
                _Updated_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated_At");
                OnUpdated_AtChanged();
            }
        }
        private global::System.DateTime _Updated_At;
        partial void OnUpdated_AtChanging(global::System.DateTime value);
        partial void OnUpdated_AtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Created_By
        {
            get
            {
                return _Created_By;
            }
            set
            {
                OnCreated_ByChanging(value);
                ReportPropertyChanging("Created_By");
                _Created_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_By");
                OnCreated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Created_By;
        partial void OnCreated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnCreated_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Updated_By
        {
            get
            {
                return _Updated_By;
            }
            set
            {
                OnUpdated_ByChanging(value);
                ReportPropertyChanging("Updated_By");
                _Updated_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated_By");
                OnUpdated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Updated_By;
        partial void OnUpdated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnUpdated_ByChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Sub_Categories_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("Acig_Help_DeskModel.FK_Sub_Categories_Categories", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Tickets_Sub_Categories", "Ticket")]
        public EntityCollection<Ticket> Tickets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ticket>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ticket>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Ticket", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Acig_Help_DeskModel", Name="Ticket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ticket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ticket object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="sub_Category_Id">Initial value of the Sub_Category_Id property.</param>
        /// <param name="created_At">Initial value of the Created_At property.</param>
        /// <param name="updated_At">Initial value of the Updated_At property.</param>
        public static Ticket CreateTicket(global::System.Int64 id, global::System.String type, global::System.String priority, global::System.String state, global::System.Int64 sub_Category_Id, global::System.DateTime created_At, global::System.DateTime updated_At)
        {
            Ticket ticket = new Ticket();
            ticket.Id = id;
            ticket.Type = type;
            ticket.Priority = priority;
            ticket.State = state;
            ticket.Sub_Category_Id = sub_Category_Id;
            ticket.Created_At = created_At;
            ticket.Updated_At = updated_At;
            return ticket;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Sub_Category_Id
        {
            get
            {
                return _Sub_Category_Id;
            }
            set
            {
                OnSub_Category_IdChanging(value);
                ReportPropertyChanging("Sub_Category_Id");
                _Sub_Category_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sub_Category_Id");
                OnSub_Category_IdChanged();
            }
        }
        private global::System.Int64 _Sub_Category_Id;
        partial void OnSub_Category_IdChanging(global::System.Int64 value);
        partial void OnSub_Category_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Assigned_To
        {
            get
            {
                return _Assigned_To;
            }
            set
            {
                OnAssigned_ToChanging(value);
                ReportPropertyChanging("Assigned_To");
                _Assigned_To = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Assigned_To");
                OnAssigned_ToChanged();
            }
        }
        private Nullable<global::System.Int64> _Assigned_To;
        partial void OnAssigned_ToChanging(Nullable<global::System.Int64> value);
        partial void OnAssigned_ToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Created_By
        {
            get
            {
                return _Created_By;
            }
            set
            {
                OnCreated_ByChanging(value);
                ReportPropertyChanging("Created_By");
                _Created_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_By");
                OnCreated_ByChanged();
            }
        }
        private Nullable<global::System.Int64> _Created_By;
        partial void OnCreated_ByChanging(Nullable<global::System.Int64> value);
        partial void OnCreated_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_At
        {
            get
            {
                return _Created_At;
            }
            set
            {
                OnCreated_AtChanging(value);
                ReportPropertyChanging("Created_At");
                _Created_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_At");
                OnCreated_AtChanged();
            }
        }
        private global::System.DateTime _Created_At;
        partial void OnCreated_AtChanging(global::System.DateTime value);
        partial void OnCreated_AtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Updated_At
        {
            get
            {
                return _Updated_At;
            }
            set
            {
                OnUpdated_AtChanging(value);
                ReportPropertyChanging("Updated_At");
                _Updated_At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated_At");
                OnUpdated_AtChanged();
            }
        }
        private global::System.DateTime _Updated_At;
        partial void OnUpdated_AtChanging(global::System.DateTime value);
        partial void OnUpdated_AtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Events_Tickets", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("Acig_Help_DeskModel.FK_Events_Tickets", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("Acig_Help_DeskModel.FK_Events_Tickets", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Acig_Help_DeskModel", "FK_Tickets_Sub_Categories", "Sub_Categories")]
        public Sub_Categories Sub_Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sub_Categories>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Sub_Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sub_Categories>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Sub_Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sub_Categories> Sub_CategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sub_Categories>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Sub_Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sub_Categories>("Acig_Help_DeskModel.FK_Tickets_Sub_Categories", "Sub_Categories", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
